### ISSUE TITLE
App aborts when deploying or running locally due to py version

### ISSUE THREAD

**Issue by oprilium** [ranikay/shiny-reticulate-app#10]
Hello,
I have been having difficulties in deploying an shiny app that contains python... I recently reinstalled everything (from R to Anaconda - I have windows btw) and some scripts that have that use Keras and Tensorflow... run well with no issue. Even creating a shiny app of that, locally, does not pose any issue. The problem arises when I try to deploy it in shinyapps.io. Not being able to find a solution myself, I saw this app and decided to give it a try. I just ran it without any modification and I am getting this error message printed in the console. Are you aware of what can be? If I run it locally without all the virtual env setups... it goes well.

`Warning in system2(python, args, stdout = TRUE, stderr = FALSE) :
  running command '"python3" -E -c "import platform; print(platform.python_version())"' had status 9009
Warning: Error in if: argument is of length zero
  49: virtualenv_module
  48: reticulate::virtualenv_create
  47: server [C:\Users\my.name\Documents\1.R_projects\shiny-reticulate-app-master/server.R#18]
Error in if (py_version >= "3.6") modules <- c("venv", modules) : 
  argument is of length zero`
  
  Thanks

**Comment by oprilium** [comment]
Also it gets deployed in shinyapps.io server but the app doesn't load. In the logs I have this same message three times:

`15749]:   Python specified in RETICULATE_PYTHON (/home/shiny/.virtualenvs/example_env_name/bin/python) does not exist
2020-12-18T14:20:01.908010+00:00 shinyapps[3415749]: Warning: Error in py_discover_config: Python specified in RETICULATE_PYTHON (/home/shiny/.virtualenvs/example_env_name/bin/python) does not exist`

**Comment by hannah-podzorski-GSI** [comment]
In  the .RProfile code try changing 'python3' to 'python3.8'. For example,

if (Sys.info()[['user']] == 'shiny'){
  #Running on shinyapps.io
  Sys.setenv(PYTHON_PATH = 'python3.8')
  Sys.setenv(VIRTUALENV_NAME = VIRTUALENV_NAME) # Installs into default shiny virtualenvs dir
  Sys.setenv(RETICULATE_PYTHON = paste0('/home/shiny/.virtualenvs/', VIRTUALENV_NAME, '/bin/python'))
  }

**Comment by ranikay** [comment]
Hi @oprilium, were you able to get your app deployed on shinyapps.io?

I just updated the code to use the latest Python 3 and pip version on available on shinyapps, which should help prevent the error that you were seeing. Try re-fetching the latest on master and let me know if that works for you!

**Comment by ichsanprmn** [comment]
Hi @ranikay I encounter the same error message here, 
I use the same exact code in your repository, but it wont run locally
