### ISSUE TITLE
Local Run App fails with Error: Tools for managing Python virtual environments are not installed

### ISSUE THREAD

**Issue by moldach** [ranikay/shiny-reticulate-app#12]
Opening the `server.R` file and clicking **Run App** produces the following error in the `R` `console`:

```
> runApp()

Listening on http://127.0.0.1:7450
Warning: Error in : Tools for managing Python virtual environments are not installed.

Install pip with:
$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$ python3 get-pip.py

Install virtualenv with:
$ python3 -m pip install --upgrade --user virtualenv


  50: stop
  49: virtualenv_module
  48: reticulate::virtualenv_create
  47: server [/home/mtg/r-projects/shiny-reticulate-app/server.R#18]
Error : Tools for managing Python virtual environments are not installed.

Install pip with:
$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$ python3 get-pip.py

Install virtualenv with:
$ python3 -m pip install --upgrade --user virtualenv
```

This is odd as running the following from the `terminal` shows that I have `virtualenv`?

```
(base) mtg@mtg-ThinkPad-P53:~/r-projects/shiny-reticulate-app$ python3 -m pip install --upgrade --user virtualenv
Requirement already satisfied: virtualenv in /home/mtg/.pyenv/versions/3.6.0/lib/python3.6/site-packages (20.4.2)
Requirement already satisfied: importlib-resources>=1.0 in /home/mtg/.pyenv/versions/3.6.0/lib/python3.6/site-packages (from virtualenv) (5.1.0)
Requirement already satisfied: filelock<4,>=3.0.0 in /home/mtg/.pyenv/versions/3.6.0/lib/python3.6/site-packages (from virtualenv) (3.0.12)
Requirement already satisfied: importlib-metadata>=0.12 in /home/mtg/.pyenv/versions/3.6.0/lib/python3.6/site-packages (from virtualenv) (1.6.1)
Requirement already satisfied: six<2,>=1.9.0 in /home/mtg/.pyenv/versions/3.6.0/lib/python3.6/site-packages (from virtualenv) (1.15.0)
Requirement already satisfied: appdirs<2,>=1.4.3 in /home/mtg/.pyenv/versions/3.6.0/lib/python3.6/site-packages (from virtualenv) (1.4.3)
Requirement already satisfied: distlib<1,>=0.3.1 in /home/mtg/.pyenv/versions/3.6.0/lib/python3.6/site-packages (from virtualenv) (0.3.1)
Requirement already satisfied: zipp>=0.5 in /home/mtg/.pyenv/versions/3.6.0/lib/python3.6/site-packages (from importlib-metadata>=0.12->virtualenv) (3.1.0)
```

**Comment by moldach** [comment]
Not sure if the error is being produced by `VIRTUALENV_NAME` as:

```
> virtualenv_dir = Sys.getenv('VIRTUALENV_NAME')
> python_path = Sys.getenv('PYTHON_PATH')
> virtualenv_dir
[1] "example_env_name"
> python_path
[1] "python3"
```

The `reticulate::virtualenv_root()` seems to show: `[1] "~/.virtualenvs"`.

Any idea what the problem is?

**Comment by moldach** [comment]
Not sure what I changed but now getting this error:

```
> runApp()

Listening on http://127.0.0.1:7450
virtualenv: example_env_name
Using virtual environment 'example_env_name' ...
Warning in system2(python, c("-c", shQuote(command)), stdout = TRUE, stderr = TRUE) :
  running command ''/home/mtg/.virtualenvs/example_env_name/bin/python' -c 'import sys; import pip; sys.stdout.write(pip.__version__)' 2>&1' had status 1
Warning in if (idx != -1) version <- substring(version, 1, idx - 1) :
  the condition has length > 1 and only the first element will be used
Warning: Error in : invalid version specification ‘’, ‘  ’
  52: stop
  51: .make_numeric_version
  50: numeric_version
  49: pip_version
  48: reticulate::virtualenv_install
  47: server [/home/mtg/r-projects/shiny-reticulate-app/server.R#19]
Error : invalid version specification ‘’, ‘  ’
```

**Comment by ranikay** [comment]
Hi @moldach , couple thoughts. 

It looks like you're creating the virtualenv but pip might not be getting installed into it, which means there might be a version/path mismatch. First, install pip3 and confirm that it's installed under Python 3:

```
python3 -m pip install --upgrade pip
pip3 --version
```
![image](https://user-images.githubusercontent.com/4951228/107437030-9a172900-6aeb-11eb-8a6e-90fde26ad5ce.png)

Then install `virtualenv` with `pip3 install virtualenv`.

Then change the `VIRUTALENV_NAME` at the top of the included `.Rprofile` file to something different so that a new environment will be created. (Whatever name you give it here will be the name of the directory created in the `reticulate::virtualenv_root()` directory). Then try running the app again!

If you still get the same error, I'd recommend going in the virtualenv and confirming whether pip is installed correctly into the environment. For example:
```
cd ~/.virtualenvs/YOUR_ENV_NAME/
source bin/activate
pip3 freeze   # should output a few packages
```

**Comment by moldach** [comment]
Hi @ranikay, thanks for the advice. I tried the following:

## Terminal

```
(base) mtg@mtg-ThinkPad-P53:~/r-projects/shiny-reticulate-app$ python3 -m venv ~/mattsNewENV
(base) mtg@mtg-ThinkPad-P53:~/r-projects/shiny-reticulate-app$ source ~/mattsNewENV/bin/activate
(mattsNewENV) (base) mtg@mtg-ThinkPad-P53:~/r-projects/shiny-reticulate-app$ python3 -m pip install --upgrade pip
Cache entry deserialization failed, entry ignored
Collecting pip
  Using cached https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-21.0.1
(mattsNewENV) (base) mtg@mtg-ThinkPad-P53:~/r-projects/shiny-reticulate-app$ pip3 --version
pip 21.0.1 from /home/mtg/mattsNewENV/lib/python3.6/site-packages/pip (python 3.6)
(mattsNewENV) (base) mtg@mtg-ThinkPad-P53:~/r-projects/shiny-reticulate-app$ python3 -m pip install --upgrade virtualenv
```

> If you still get the same error, I'd recommend going in the virtualenv and confirming whether pip is installed correctly into the environment. 

Might as well just do this to confirm that the Python package `virtualenv` is contained within this created environment.

```
# Restart shell
(mattsNewENV) (base) mtg@mtg-ThinkPad-P53:~/mattsNewENV$ exec $SHELL
# Enter environmet
(base) mtg@mtg-ThinkPad-P53:~/mattsNewENV$ cd ~/mattsNewENV/
(base) mtg@mtg-ThinkPad-P53:~/mattsNewENV$ source bin/activate
# check for installed modules
(mattsNewENV) (base) mtg@mtg-ThinkPad-P53:~/mattsNewENV$ pip3 freeze
appdirs==1.4.4
distlib==0.3.1
filelock==3.0.12
importlib-metadata==3.4.0
importlib-resources==5.1.0
six==1.15.0
typing-extensions==3.7.4.3
virtualenv==20.4.2
zipp==3.4.0
```

We can see that `virtualenv==20.4.2` is available in the environment, so next we make changes:

### Change `.Rprofile` included with repo

```
# Edit this name if desired when starting a new app
VIRTUALENV_NAME = 'shiny-reticulate-test'
```

Finally, Save, Restart R (Ctrl + Shift + F10), and then try and run the app.

### RunApp

```
> shiny::runApp()
Loading required package: shiny

Listening on http://127.0.0.1:7450

Attaching package: ‘DT’

The following objects are masked from ‘package:shiny’:

    dataTableOutput, renderDataTable

Warning: Error in : Tools for managing Python virtual environments are not installed.

Install pip with:
$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$ python3 get-pip.py

Install virtualenv with:
$ python3 -m pip install --upgrade --user virtualenv


  50: stop
  49: virtualenv_module
  48: reticulate::virtualenv_create
  47: server [/home/mtg/r-projects/shiny-reticulate-app/server.R#18]
Error : Tools for managing Python virtual environments are not installed.

Install pip with:
$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$ python3 get-pip.py

Install virtualenv with:
$ python3 -m pip install --upgrade --user virtualenv
```

**Comment by ranikay** [comment]
> We can see that virtualenv==20.4.2 is available in the environment

Are you trying to create a virtual environment _within_ another virtual environment? The overall process we're trying to achieve here should be just 1) create a `virtualenv` in the `~/.virtualenvs` directory, 2) tell R to use that `virtualenv` when executing Python code.

It looks like you already have an environment that you were introspecting called `mattsNewENV`. It doesn't matter whether the `virtualenv` package is installed in this environment just as long as it has `pip`, which it appears to have since `pip3 freeze` worked. You'll also want to install `pip3 install numpy` into `mattsNewENV` since it's a requirement for this app tutorial.

Then, since you already have that environment with `pip` and `numpy` installed and working, in your .Rprofile you should be able to define `VIRTUALENV_NAME = 'mattsNewENV'` instead of `VIRTUALENV_NAME = 'shiny-reticulate-test'` as you had it written. This will tell R to use the (already created) `mattsNewENV` environment.

P.S. Thanks for calling out that you always need to restart your R session after making changes, as this is required to re-load the .Rprofile file.

**Comment by moldach** [comment]
> Are you trying to create a virtual environment within another virtual environment?

`Python` inception ... 🤔 No... sorry, not on purpose.


My solution - comment out the section of your code that said not too 🤣 

```
conda create -n ranikay
conda activate ranikay
conda install -c anaconda numpy
```

Then edit the `server.R` script:

```
  # ------------------ App virtualenv setup (Do not edit) ------------------- #
  
  # virtualenv_dir = Sys.getenv('VIRTUALENV_NAME')
  # python_path = Sys.getenv('PYTHON_PATH')
  # 
  # # Create virtual env and install dependencies
  # reticulate::virtualenv_create(envname = virtualenv_dir, python = python_path)
  # reticulate::virtualenv_install(virtualenv_dir, packages = PYTHON_DEPENDENCIES, ignore_installed=TRUE)
  # reticulate::use_virtualenv(virtualenv_dir, required = T)
  # ------------------ App server logic (Edit anything below) --------------- #
 
  reticulate::use_condaenv("ranikay")
  ```
  
You can either create `virtualenv` (`python3 -m venv ~/myEnv`) followed by installing `numpy` with `pip`, or using `conda`, and use the `use_virtualenv()` or `use_conda()` instead.

P.S. Nice snowboarding profile picture BTW - have fun shredding this season - cheers, [from an avid rider](https://moldach.github.io/post/faststyletransfer/) 🤙

**Comment by ranikay** [comment]
Ha, sometimes the best solutions include breaking rules and forging your own path 😉 🤙 

Glad you got it figured out!
