### ISSUE TITLE
Specific version of packages virtualenv

### ISSUE THREAD

**Issue by mfumagalli68** [ranikay/shiny-reticulate-app#2]
Hi great tutorial.

I posted a question on SO.
https://stackoverflow.com/questions/60882638/install-a-particular-version-of-python-package-in-a-virtualenv-created-with-reti

Do you know if we can specify a particular version of  packages installed inside virtualenv?

Thanks

**Comment by ranikay** [comment]
Good question! Glad to see that it was answered so quickly on SO. 

For anyone else who comes across this issue, you can use pip-like syntax for each package inside the `virtualenv_install` function. For example:

`reticulate::virtualenv_install(packages = c("numpy==1.8.0", "requests==2.22.0"))`
